### ISSUE TITLE
Cannot Install Ubuntu 16.10

### ISSUE THREAD

**Issue by jrock2004** [wavexx/screenkey#41]
So I cloned the master repo and when I do `./screenkey` it runs perfectly. Not I want to install it `sudo./setup.py install` I get an error

```
Traceback (most recent call last):
  File "./setup.py", line 35, in <module>
    ('share/doc/screenkey', ['README.rst', 'NEWS.rst'])],
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 348, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 394, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 851, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1135, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 459, in fetch_build_egg
    cmd.ensure_finalized()
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 289, in finalize_options
    'site_dirs',
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1364, in _expand
    config_vars = self.get_finalized_command('install').config_vars
  File "/usr/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/lib/python2.7/distutils/command/install.py", line 395, in finalize_options
    ('build_lib', 'build_lib'))
  File "/usr/lib/python2.7/distutils/cmd.py", line 297, in set_undefined_options
    src_cmd_obj = self.distribution.get_command_obj(src_cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 856, in get_command_obj
    self._set_command_options(cmd_obj, options)
  File "/usr/lib/python2.7/distutils/dist.py", line 899, in _set_command_options
    % (source, command_name, option))
distutils.errors.DistutilsOptionError: error in setup.cfg: command 'build' has no such option 'i18n'

```

**Comment by jrock2004** [comment]
Sorry, rookie mistake. Did not install dependencies
